name: Create release
on:
  push:
    branches:
      - main
    paths:
      - '**provider**'
jobs:
  main:
    runs-on: ubuntu-latest
    environment:
      name: Semver
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        run: npm install semantic-release;npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
