name: Create new release
permissions:
  contents: write
  actions: read
  pull-requests: write
on:
  push:
    branches:
      - main
    paths:
      - '**provider**'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Semantic Release
        run: npm install semantic-release;npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
